# Generated by Django 5.0.1 on 2024-01-20 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus', models.TextField()),
                ('seatplanleft', models.IntegerField()),
                ('seatplanright', models.IntegerField()),
                ('seatplanrows', models.IntegerField()),
                ('operations_day', models.IntegerField()),
                ('costmultiplier', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationname', models.TextField()),
                ('coordinatesx', models.IntegerField()),
                ('coordinatesy', models.IntegerField()),
                ('city', models.TextField()),
                ('state', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Seats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rownumber', models.IntegerField()),
                ('colnumber', models.IntegerField()),
                ('isoccupied', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('password', models.TextField()),
                ('isadmin', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromstop', models.TextField()),
                ('tostop', models.TextField()),
                ('distance', models.IntegerField()),
                ('cost', models.IntegerField()),
                ('time', models.DateTimeField()),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.bus')),
            ],
        ),
        migrations.CreateModel(
            name='Stops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stopname', models.TextField()),
                ('arrivaltime', models.DateTimeField()),
                ('departuretime', models.DateTimeField()),
                ('busid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.bus')),
                ('locationid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.location')),
            ],
        ),
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seatrow', models.IntegerField()),
                ('seatcol', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('departuretime', models.DateTimeField()),
                ('arrivaltime', models.DateTimeField()),
                ('busid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.bus')),
                ('fromstop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromstop', to='api.location')),
                ('tostop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tostop', to='api.location')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.users')),
            ],
        ),
    ]
