# Generated by Django 5.0.1 on 2024-01-20 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_bus_location_seats_users_routes_stops_bookings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='fromstop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fromstop', to='api.stops'),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='tostop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tostop', to='api.stops'),
        ),
    ]
