# Generated by Django 4.1.3 on 2024-01-20 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_stops_stopname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='routes',
            name='busId',
        ),
    ]
