# Generated by Django 4.1.3 on 2024-01-20 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_routes_busid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='coordinatesX',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='location',
            name='coordinatesY',
            field=models.FloatField(),
        ),
    ]
